services:
  webserver:
    image: linux2-web
    networks:
      - linux2-net

  client:
    image: ubuntu
    command: sleep infinity
    networks:
      - linux2-net

networks:
  linux2-net:
    external: true
