version: "3.9"

services:
  db:
    image: postgres:16
    container_name: miladbooks-db-1
    environment:
      POSTGRES_USER: milad
      POSTGRES_PASSWORD: milad123
      POSTGRES_DB: miladbooks
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    container_name: miladbooks-backend-1
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: miladbooks-frontend
    container_name: miladbooks-frontend-1
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres-data:
  backend-logs:
